# Generated by Django 5.2.4 on 2025-07-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='comleted',
            new_name='completed',
        ),
    ]
