# Generated by Django 5.2.4 on 2025-07-17 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_trackanswer_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='trackanswer',
            name='likes',
        ),
    ]
