# Generated by Django 5.2.4 on 2025-07-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_rename_comleted_track_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='category',
        ),
        migrations.AddField(
            model_name='track',
            name='category',
            field=models.ManyToManyField(related_name='tracks', to='track.trackcategory'),
        ),
    ]
